name: Lizp Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-hello:
    name: Test hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run multi-line script - test-hello
        run: |
          sudo apt install sbcl
          mkdir -p ${HOME}/quicklisp/local-projects
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/edicl/hunchentoot.git
          make quicklisp
          sbcl --noinform --no-userinit --no-sysinit --non-interactive --load src/hello.lisp
      - name: run multi-line script - test-goodbye
        run: |
          sudo apt install sbcl
          mkdir -p ${HOME}/quicklisp/local-projects
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/edicl/hunchentoot.git
          make quicklisp
          sbcl --noinform --no-userinit --no-sysinit --non-interactive --load src/goodbye.lisp
